version: '3.9'

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./apache/Dockerfile 
    ports:
      - 80:80
    volumes:
      - ./apache/vhosts:/usr/local/apache2/vhosts
  
  todolist:
    image: node:alpine
    container_name: todolist
    entrypoint: /bin/sh
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true