version: '3.9'

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: ./apache/Dockerfile 
    ports:
      - 80:80
    volumes:
      - ./apache/vhosts:/usr/local/apache2/vhosts

